### ISSUE TITLE
Digitize Abhyankar' sanskrit dictionary

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/sanskrit-ocr-r0#1]
Welcome! Answer all these questions.

Do you want a text OCR-ed? If yes continue below. If not, clear all this text and type your issue.
- Has the text already been OCR-ed? Have you searched online (using both devanAgarI and latin transliterations)? No and Yes.
  - For example in the large repositories of digitized texts listed [here](https://sites.google.com/site/samskrtamsfo/home/prakashanani/pathyam#TOC---Digitized-texts).
- What factors should our OCR/ other volunteers consider when deciding whether to take up this request? In other words, what's so important about this text? Very valuable for students of Sanskrit Grammar.
- Are you willing to proofread the OCR-ed text? See [here](https://sites.google.com/site/sanskritcode/ocr/3-corrections) to get an idea of what it involves. No.
- Provide a link to the pdf of the _printed_ book which needs to be OCR-ed. You can host the pdf online on several sites such as <dropbox.com> or <sites.google.com> . https://archive.org/stream/ADictionaryOfSanskritGrammarByMahamahopadhyayaKashinathVasudevAbhyankar/DictionaryOfSanskritGrammar_abhyankar#page/n0/mode/2up
- Is there any other information you want to provide? No.

Ok - thanks for answering the above questions. Subscribe to this thread to stay updated.

**Comment by vvasuki** [comment]
OCR done: https://raw.githubusercontent.com/sanskrit-coders/sanskrit-ocr-r0/master/vaak/vyAkaraNam/abhyankar-grammar/abhyankar-grammar-gocr.txt

Readme for the book: https://github.com/sanskrit-coders/sanskrit-ocr-r0/tree/master/vaak/vyAkaraNam/abhyankar-grammar
- Text title: A DICTI0NARY OF SANSKRIT GRAMMAR
- Author:  Mahimahopadhyaya KASHINATH VASUDEV ABHYANKAR
- Pdf/ archive link [here](https://archive.org/stream/ADictionaryOfSanskritGrammarByMahamahopadhyayaKashinathVasudevAbhyankar/DictionaryOfSanskritGrammar_abhyankar#page/n0/mode/2up).
- OCR-ed text
  - gocr: Better english worse sanskrit [here](https://raw.githubusercontent.com/sanskrit-coders/sanskrit-ocr-r0/master/vaak/vyAkaraNam/abhyankar-grammar/abhyankar-grammar-gocr.txt).
  - gocr: Better sanskrit worse english [here](https://raw.githubusercontent.com/sanskrit-coders/sanskrit-ocr-r0/master/vaak/vyAkaraNam/abhyankar-grammar/abhyankar-grammar-gocr-sa.txt).
- Proofreading setup on wikisource:
  - [djvu file](https://commons.wikimedia.org/wiki/File:ADictionaryOfSanskritGrammarByMahamahopadhyayaKashinathVasudevAbhyankar.djvu)
  - [wikisource index](https://sa.wikisource.org/wiki/%E0%A4%85%E0%A4%A8%E0%A5%81%E0%A4%95%E0%A5%8D%E0%A4%B0%E0%A4%AE%E0%A4%A3%E0%A4%BF%E0%A4%95%E0%A4%BE:ADictionaryOfSanskritGrammarByMahamahopadhyayaKashinathVasudevAbhyankar.djvu)
- Tracking issue: [here](https://github.com/sanskrit-coders/sanskrit-ocr-r0/issues/1).
- Notes for proofreaders:
  - Please consider priorities and guidelines described [here](https://sites.google.com/site/sanskritcode/ocr/3-corrections#TOC-In-dictionary-type-files).

**Comment by vvasuki** [comment]
vidyajay@gm is proofreading this on wikisource.

**Comment by vvasuki** [comment]
namaste vidya, I am developing a bot to copy over the OCR text automatically to the wikisource pages. would you like this to be done on the pages you haven't reviewed so far?

**Comment by drdhaval2785** [comment]
@vvasuki I would like to use the bot to upload the OCR text for gaNaratnamahodadhiH which I created via SanskritOCR named as (00001.txt, 0002.txt.....) to the wikisource pages. 
I would be glad if some tool can do it automatically / semi automatically.

**Comment by vvasuki** [comment]
I haven't finished writing the bot yet, but will do so soon. @drdhaval2785  will follow up on the other issue thread you opened.

**Comment by vidyajay** [comment]
Yes, If we can update only those pages say starting from Page 25 that are either marked as 'not proofed' or 'some issues with this page (this I use for work-in-progress) pages, then it would be convenient.

**Comment by vidyajay** [comment]
Jihvamuliya and upadhmaniya don't seem to have browser support, unless a font such as siddhanta/chandas is used. Any suggestions for proofreaders on what to use when encountering these two characters in digtized texts.

**Comment by vvasuki** [comment]
Just use the right characters even if you see just a box for now. The browser/ font issue is separate from the unicode encoding/ digitization issue.

**Comment by vvasuki** [comment]
Added about 10 pages - Wikipedia is ratelimiting the bot. So, filed this: 
Bot approval request: https://en.wikipedia.org/wiki/Wikipedia:Bots/Requests_for_approval/sanskritnlpbot

**Comment by vvasuki** [comment]
@vidyajay - I uploaded those OCR page texts from the "better english worse sanskrit scan" - is that what you preferred?

**Comment by vidyajay** [comment]
@vvasuki Yes, The better English worse Sanskrit works better for the purpose of proof-reading.

**Comment by drdhaval2785** [comment]
Did your bot get complete and approved @vvasuki?

**Comment by vvasuki** [comment]
2016-03-01 19:59 GMT-08:00 Dr. Dhaval Patel notifications@github.com:

> Did your bot get complete

​yes, for gocr.​

> and approved @vvasuki?

​not yet. but that only means that the bot can upload OCR ​pages at a much
slower (still probably good-enough for proofreading) pace.

## 

## 

Vishvas /विश्वासः

**Comment by vvasuki** [comment]
OCR for all pages now uploaded. I've also written to the publisher for formal digitization permission.

**Comment by vidyajay** [comment]
Is it possible to replace page 44 with a better scan? In a few places, where the text wasn't clear I looked up the mulam and confirmed them. This page in particular is very difficult to read.

**Comment by vvasuki** [comment]
मूलम् नाम किम्? https://archive.org/stream/ADictionaryOfSanskritGrammarByMahamahopadhyayaKashinathVasudevAbhyankar/DictionaryOfSanskritGrammar_abhyankar#page/n43/mode/1up इति दृष्टं खलु? - तत्राक्षरगात्रवर्धनं शक्यम्।

दुरादृष्टवशान् नास्ति तत् पुस्तकं मम सकाशे। किन्तु, अहं तत्रत्यपाठमनुमातुं शक्नोमि - यदि क्लेशोऽनुभूयत इदानीमपि वदतु। तं पृष्ठं स्वयं शोधयिष्यामि।

**Comment by vidyajay** [comment]
बाढम् । इदानीमेव archive.org दृश्टम् । अक्षरगात्रवर्धनं कृत्वा तथैव
शोधयिष्यामि । उपायार्थं धन्यवादाः ।

विद्या

**Comment by vvasuki** [comment]
मान्ये विद्ये, अभिनन्दामि भवत्याः पाठशोधन-दक्षताम्। दृष्टमेव यद् उपषष्ठिपृष्ठानि शोधितानि। तत्र काचित् प्रार्थना - विकिस्रोतᳶप्रयोक्तॄणां कृते सम्यग्दर्शनार्थं शोधितस्य पाठस्य, कृपया प्रतिपृष्ठम् `<poem> </poem>` इत्येतयोर् मध्ये शोधितं पाठं रक्षतु। तत्रोदाहरणम् [इदमशोधितपृष्ठम्](https://sa.wikisource.org/w/index.php?title=%E0%A4%AA%E0%A5%81%E0%A4%9F%E0%A4%AE%E0%A5%8D:ADictionaryOfSanskritGrammarByMahamahopadhyayaKashinathVasudevAbhyankar.djvu/%E0%A5%A7%E0%A5%AA%E0%A5%AE&action=edit)।

**Comment by vvasuki** [comment]
नमो विद्ये 🙏
७० पृष्ठानि परिष्कृतानि दृश्यन्ते - साधु। सावकाशमनुवर्तताम्!

**Comment by vvasuki** [comment]
[सन्त्यन्येऽपि संलग्ना](https://sa.wikisource.org/w/index.php?title=%E0%A4%AA%E0%A5%81%E0%A4%9F%E0%A4%AE%E0%A5%8D:ADictionaryOfSanskritGrammarByMahamahopadhyayaKashinathVasudevAbhyankar.djvu/%E0%A5%AF%E0%A5%A9&action=history) अत्रेति दृष्ट्वा महामोदः!

**Comment by vidyajay** [comment]
विश्वास, 

विश्वास,  क्षम्यताम् काचित् व्यस्ता आसम् | पाठशोधनकार्ये विलम्बो जातः | पुनर्प्रारम्भः कृतम | 

1) विकिस्रोतस्थले 'dyuh', 'dguH', 'ddhuH' इत्यादीनि सन्ध्यक्षराणि कथं 
ठङ्कनीयम्? येनकेन प्रकारेणापि तेषां साधुरूपाणि न दृश्यन्ते | 
उदाहरणार्थम् : द्युः, द्गुः

2) अपि च - पृष्टक्रमं  १२८  - परिष्कृतमिति संलक्षितोस्ति किन्तु अपरिष्कृतमेव दृश्यते | दोषाः अनेकाः वर्तते | किं करणीयम्? 

विद्या

**Comment by vvasuki** [comment]
नमो नमः विद्ये! तोषाय यदनुवर्तयितुमधुना कार्यं समर्था भवतीति!

१। अत्र यथोट्टङ्कनं करोति तेनैव क्रमेण तत्र कुतो न भवति?

२। अधो भागे वर्तमानेन विकल्पकीलकेनेदं समीकर्तुं शक्यम्। तच्चाधुना कृतम् -
![image](https://cloud.githubusercontent.com/assets/2664797/19583236/c9d773c2-96ef-11e6-9875-843ae31db3bb.png)

**Comment by vidyajay** [comment]
१। अत्र यथोट्टङ्कनं करोति तेनैव क्रमेण तत्र कुतो न भवति?

Browser-issue. Problem solved.
