### ISSUE TITLE
Expected project outcome and prodecures

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/sanskrit-ocr-r0#2]
@vvasuki 
As I can see from the discussions on mail and here, this seems not only restricted to a single book OCRing, but something larger for crowdsourcing Sanskrit / bilingual texts.
Therefore, we need to decide on expected outcomes and processes. Feel free to edit the below mentioned things. They are only suggestive.

Expected outcome
1. A machine which can take in PDF as input and give pagewise .txt (unicode) as output
2. The OCR should have good dictionaries for better output.
3. An HTML frontend on which the people can edit and correct.
4. A user management system and some kind of history keeping for changes made.

Procedures
1. Which computer language to adopt ?
2. Stand alone tool / online tool / a wrapper on existing tools ?

**Comment by vvasuki** [comment]
आत्मीय, साधु चिन्त्यते।

अभियान्त्रिकवृत्तेस् तु प्रथमो नियमः - आमूलयन्त्रनिर्माणाद् अन्ययन्त्रप्रयोग उत्तरः। (never reinvent the wheel.) तेन,
Expected outcome
1. A machine which can take in PDF as input and give pagewise .txt (unicode) as output
न। यन्त्राणि सन्ति पूर्वमेव। तत्प्रयोक्तार एवावश्यकाः।
2. The OCR should have good dictionaries for better output.
साधु विचारः, किन्त्वस्यां योजनापरिधौ नास्ति।
3. An HTML frontend on which the people can edit and correct.
न। यन्त्राणि सन्ति पूर्वमेव। तत्प्रयोक्तार एवावश्यकाः। (wikisource)
4. A user management system and some kind of history keeping for changes made.
न। यन्त्राणि सन्ति पूर्वमेव। तत्प्रयोक्तार एवावश्यकाः। (github)

इतोऽपि विवरणान्य् अत्रेक्षस्व - https://sites.google.com/site/sanskritcode/ocr/0-introduction

**Comment by drdhaval2785** [comment]
In that case, please specify the softwares to be used in each step.
Ambiguity may lead to confusion.
1. OCR - some kind of OCR available at yr workplace or SanskritOCR?
2. Preupload regex modifications
3. Wiki or pgdp?

**Comment by vvasuki** [comment]
Actually there's no confusion, as long as one specifies the tool used. Not having restrictions encourages people to try out different tools. For the OCR tasks I'm handling, I can currently do OCR at my workplace, and set up wikisource (seems much simpler than pgdp). But others can do something else, if they prefer.

Will [open a new issue](https://github.com/sanskrit-coders/sanskrit-ocr-r0/issues/3) to save and apply common regex-fixes before handing over the digitized text for proof-reading.
