### ISSUE TITLE
Digitize गणरत्नमहोदधिः

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/sanskrit-ocr-r0#4]
Welcome! Answer all these questions.

Do you want a text OCR-ed? If yes continue below. If not, clear all this text and type your issue.
- Has the text already been OCR-ed? Have you searched online (using both devanAgarI and latin transliterations)? For example in the large repositories of digitized texts listed [here](https://sites.google.com/site/samskrtamsfo/home/prakashanani/pathyam#TOC---Digitized-texts).
  - **Answer**: Yes. Not digitized
- If you commit to proof-read the result within a reasonable timeframe (say 1 month for 300 pages), we will be specially excited to oblige you. Are you willing to make such a commitment? See [here](https://sites.google.com/site/sanskritcode/ocr/3-corrections) to get an idea of what it involves.
  - **Answer**: Yes
- Are you OK with the scan quality that we [currently offer](https://sites.google.com/site/sanskritcode/ocr/0-introduction#TOC-What-scan-quality-can-you-currently-offer-)?
  - **Answer**: No. I will use a private SanskritOCR to OCR.
- What other factors should our OCR/ other volunteers consider when deciding whether to take up this request? In other words, what's so important about this text?
  - **Answer**: This is a commentary on गणपाठः
- Provide a link to the pdf of the _printed_ book which needs to be OCR-ed. You can host the pdf online on several sites such as http://dropbox.com or http://sites.google.com .
  - **Answer**:  https://sa.wikisource.org/wiki/%E0%A4%B8%E0%A4%9E%E0%A5%8D%E0%A4%9A%E0%A4%BF%E0%A4%95%E0%A4%BE:Ganaratnamahodadhi.pdf
- Now for some details: please enter the following metadata (use both devanAgarI and latin alphabet forms if you can).
  - **Title**: गणरत्नमहोदधिः (gaNaratnamahodadhiH)
  - **Author**: वर्धमानकविः (VardhamanakaviH)
  - **Commentator**: -
- Is there any other information you want to provide?
  - **Answer**:

Ok - thanks for answering the above questions 🙏. Subscribe to this thread to stay updated.

**Comment by vvasuki** [comment]
Dear dhaval - You've not created the index page correctly. You need to do the steps described [here](https://en.wikisource.org/wiki/Help:Beginner%27s_guide_to_adding_texts) and summarized [here](https://sites.google.com/site/sanskritcode/ocr/3-corrections).

My suggestion is - upload it first to archive. Then use the IA-Upload tool to import it to Wikimedia Commons (separate from the sanskrit wikisource). Then create an index page in the sanskrit wikisource.

**Comment by drdhaval2785** [comment]
I guess the issue is not about creating index page correctly.
It has more to do regarding wikisource site not rendering Sanskrit OCR text from Sanskrit PDF files.
The first English page was created well. 
https://sa.wikisource.org/wiki/%E0%A4%85%E0%A4%A8%E0%A5%81%E0%A4%95%E0%A5%8D%E0%A4%B0%E0%A4%AE%E0%A4%A3%E0%A4%BF%E0%A4%95%E0%A4%BE:Ganaratnamahodadhi.pdf seemed fine to me.

**Comment by vvasuki** [comment]
- Ok! Thanks for correcting me: I had mistook the file page for an index page. The index page (which you call " first English page") seems fine to me too. That's good enough for later transclusion.
- I did not know that you can include OCR text in pdf files! Can you please provide it separately (so that I can supply it to my bot, once it is finished)?

**Comment by vvasuki** [comment]
OCR uploaded to wikisource.

**Comment by Shreeshrii** [comment]
Vishwas,
Where is the index page for this book?

I only see
https://sa.wikisource.org/wiki/%E0%A4%B5%E0%A4%BF%E0%A4%B6%E0%A5%87%E0%A4%B7%E0%A4%83:%E0%A4%95%E0%A4%BF%E0%A4%AE%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0_%E0%A4%B8%E0%A4%AE%E0%A5%8D%E0%A4%AC%E0%A4%A6%E0%A5%8D%E0%A4%A7%E0%A4%82%E0%A4%95%E0%A4%B0%E0%A5%8B%E0%A4%A4%E0%A4%BF/%E0%A4%B8%E0%A4%9E%E0%A5%8D%E0%A4%9A%E0%A4%BF%E0%A4%95%E0%A4%BE:Ganaratnamahodadhi.pdf

**Comment by vvasuki** [comment]
Index page is broken: https://sa.wikisource.org/wiki/%E0%A4%85%E0%A4%A8%E0%A5%81%E0%A4%95%E0%A5%8D%E0%A4%B0%E0%A4%AE%E0%A4%A3%E0%A4%BF%E0%A4%95%E0%A4%BE:Ganaratnamahodadhi.pdf .

Reason: dhaval's pdf upload is gone. Probably one needs to reupload and create an index page - see links in https://github.com/sanskrit-coders/sanskrit-ocr-r0/issues/4#issuecomment-190284655

**Comment by drdhaval2785** [comment]
As far as I know, some Devanagari lover changed filename to Devanagari.
Please search with debanagari script
