### ISSUE TITLE
Documentation of steps for using SanskritOCR

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/sanskrit-ocr-r0#8]
If one decides to use SanskritOCR for scanning purpose, the following steps may be useful.

Step 1 - Open the folder containing SanskritOCR. Repleace the existing dictionary-sa.dict with the [present file](https://github.com/sanskrit-coders/sanskrit-ocr-r0/blob/master/SanskritOCR/dictionary-sa.dict). If you are a bit uncomfortable in changing a software, please take a backup of the old dictionary-sa.dict file somewhere in case you want to roll back.

Step 2 - Split the PDF file you want to scan into separate .tiff files. I use [Irfanview](http://www.irfanview.com/). The following are steps in irfanview. It may differ with different softwares.

Step 2a - Open the .pdf file in irfanview.

Step 2b - Click on Options->Multipage images->Extract all pages. Select the folder where you want to extract the pages. Select .tiff for output. Run it. This will extract all pages in the folder separately.

Step 3 - Open SanskritOCR.exe.

Step 4 - Select File->New images and select a decently scanned page to train OCR.

Step 5 - Select Image->Remove irregular noise.

Step 6 - Select Recognition->Training set->New training set->Enter some name for you to understand (e.g. ganaratna)->Save and close.

Step 7 - Select the training set from list and click on 'Select as training set'.

Step 8 - Click on Recognition -> Training mode. (This will activate the training mode). Whenever machine doesn't understand a letter, it will ask for us to input the letter and store it.

Step 9 - Click on Recognition -> Recognize current page.

Step 10 - Whenever the machine asks you for input and you recognize the letter, note in the window. Sample case is attached here.
![capture](https://cloud.githubusercontent.com/assets/5755132/13561224/7a03e76a-e450-11e5-9b8b-0fc2ab7dd0a7.png)

Step 11 - Complete training the present page.

Step 12 - Repeat the process for 5-10 pages. This would make machine understand some of the odd patterns in the font glyphs. After 5-10 pages, our machine has some idea of the structure of the glyph being scanned. Now we are good to do batch conversion.

Step 13 - Click on Recognition->OCR a complete directory.

Step 14 - Select the 'Source directory', Set 'Export format' as 'Multiple unicode text files (numbered)', Select 'save in/as' to the directory where you want to store the output. Click on 'Start OCR'. This will do batch conversion.
![capture](https://cloud.githubusercontent.com/assets/5755132/13561279/1eeb3e04-e451-11e5-8399-394ad851271c.png)

Output would be stored in 0001.txt, 0002.txt etc format.

Then @vvasuki 's NLP bot may place the data on wikisource.

**Comment by vvasuki** [comment]
Thanks! I've linked to this [page here](https://sites.google.com/site/sanskritcode/ocr/1-ocr-ing?pli=1).

**Comment by shrivathsa** [comment]
Many a time, working with whole directories doesn't do a good job of segmenting the text properly. I had raised this issue with Olivier but his response forced me to fall back on manual marking of pages.
