### ISSUE TITLE
OCR ekAgnikANDa

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/sanskrit-ocr-r0#9]
The ekAgnikANDa text is essential for all practitioners of the Apastamba gRhya-sUtra (links [here](https://github.com/sanskrit-coders/sanskrit-ocr-r0/tree/master/kalpa/ekAgnikANDaH) ). But alas, it is not digitized!

@shrivathsa - could you please give this a shot? I wonder if SanskritOCR is sufficiently good with accented text..

**Comment by shrivathsa** [comment]
Isn't the ekAgnikANDa digitized by parankusa people? I have the text with me and will upload.

**Comment by vvasuki** [comment]
That's wonderful - I did not know, please do upload.

​​
But it may be good to proceed with the digitization as:
- haradatta's commentary is important to have. I for one always work to understand the mantra-s before prayoga-s.
- And this would be a good test of sanskritocr's abilities with accented text.

If training sanskritocr for good accented text recognition turns out to be a pain, you can just give up on that part (but tell us about your experience) and just focus on getting the unaccented text in the commentary right. We can then combine it with the parAnkusha text.
